### ISSUE TITLE
Elyra Pipeline Editor 2.0 (umbrella issue)

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1002]
Enhance the current Elyra Pipeline Editor to better accommodate:
 - Multiple runtimes including different behavior from specific runtime
 - Simplify the addition of new components to the pipeline palette
   - Different runtimes might have a different set of supported components

Discussions: 
These RFCs are a lot to dig into, so I've tried to summarize them here.
I think this can be broken up into 3 parts:
- the actual schema
- where does the info come from
- how does the pipeline editor handle information

###  the actual schema
For the actual schema see the RFCs

### how does the pipeline editor handle information
The PipelineEditor component will not be aware of “runtimes”
the PipelineEditor will only receive: 
- a list of nodes
- a configuration, which is basically:
    - a list of what nodes are valid and the severity for an invalid node type
    - a list of exported “shared” properties that can be optionally used by any node (think runtime image)
    - a list of property overrides that will override a specific property for the given node
    - a list of property globals that will be applied to all nodes

### where does the info come from
All of our editors need access to the same information and preferably access without `elyra` being installed. For example, the vscode extension doesn't guarantee `elyra` being installed  and the browser extensions will not have `elyra` installed. For that reason I think we need to split things into two groups: `core` and `3rd party`. The core nodes/configs will be installed via pip/npm. 3rd party nodes/config will be handled similar to metadata 

### RFCs
- Node schema for pipelines 2.0 #1444
- Runtime schema for pipelines 2.0 #1520
- Properties schema for pipelines 2.0 #1519
- ~~Linting for pipelines 2.0 #1518~~ (Defered)
- Node registry for pipelines 2.0 #1521

Some of the items that need to be addressed are:

Infrastructure:
- [x] Release https://github.com/elyra-ai/pipeline-editor
- [x] Integrate pipeline-editor components with Elyra #1221
- [x] Move serving pallete.json and properties.json to server #454 
- [x] Add REST API to parse pipeline artifacts and provide artifact metadata #957 
- [ ] create an Elyra theme supporting light/dark mode and be used across all components (related to #1428)

Phase 1:
- [x] Enable creation of pipelines specific to a runtime #1003 
- [x] Refactor Common-Properties 
- [x] Refactor pipeline validation #1592
   - [x] Node validation should be based on runtime/operation #870 
   - [x] Validation should detect unsupported nodes #938
   - [x] Enhance pipeline backend validation #1370
   - [x] Ensure no invalid values are persisted to pipeline (related to #1426 and #925)
- [ ] Update/Improve Elyra tutorials and documentation

Phase 2:
- [x] Add support for pipeline runtime specific components #1004
- [x] Pipeline validation should detect nodes that are not supported #938 
- [ ] Document best practice for implementing UI components #1594
   - [ ] Refactor business logic from UI components #1405
- [ ] Update/Improve Elyra tutorials and documentation

**Comment by lresende** [comment]
@akchinSTC should this have been closed with the merge of #1664

**Comment by lresende** [comment]
Major items are done, remaining non-blocking issues are scheduled for future sprints.
