### ISSUE TITLE
Enable adding R Scripts to pipelines

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#1424]
**Describe the issue**

Similar to how we now support Python Scripts as pipeline nodes, R scripts are also very popular and should be supported in the pipeline editor.

**Tasks**

- [x] Enable drag and drop of R scripts to pipeline editor
- [x] Enable running pipelines in KFP, Airflow, and local mode
- [x] Add/Install sample R runtime-image 

**Pipeline Editor example**

![image](https://user-images.githubusercontent.com/382917/110979020-f0f56580-8318-11eb-9f42-2e0b5b9c5abb.png)
