### ISSUE TITLE
Add Scala editor to Elyra

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#2867]
**Is your feature request related to a problem? Please describe.**
This is a umbrella issue to add a Scala editor feature to elyra

**TODO**

- [ ] Initial changes for scala editor https://github.com/elyra-ai/elyra/pull/2850
- [ ] Scala editor will be installed alongside the other editors currently. We want to make it an optional package so that users can pick and choose what editors they want to enable as part of the installation. This feature can be extended to provide the same ability to all editors
- [ ] Add `run-as-pipeline` button to scala editor
- [ ] Add Scala editor to conda-forge

**Describe alternatives you've considered**

**Additional context**
