### ISSUE TITLE
Discover ENVs used in nb when displaying property tab on Pipeline editor in other languages

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#385]
When submitting an individual notebook, we parse the notebook and display a list of environment variables and allow users to add values, but when working on the pipelines, we don't have that option enabled. 

For parity, we should also enable it.

Related Issues:

- [ ] https://github.com/elyra-ai/elyra/issues/444 - Env vars is not always populated when adding a notebook to a pipeline
- [ ] https://github.com/elyra-ai/elyra/issues/710 - Pipeline node properties does not recognize new environment variables
- [ ] https://github.com/elyra-ai/elyra/issues/1285 - Parsing of environment variables from notebook pipeline component fails

**Comment by akchinSTC** [comment]
PR #202 resolves the issue with parsing envs in a python environment however we should start looking ahead into other languages we will be supporting in the future

**Comment by romeokienzler** [comment]
@akchinSTC I'd like to vote for adding ENVs from bash cells withing python notebooks first

so 

%%bash

and

!

cell should be supported

**Comment by ajbozarth** [comment]
Related frontend PR https://github.com/elyra-ai/elyra/issues/1285
