### ISSUE TITLE
Add Python/R Editor front end tests

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#536]
Initial test scenarios (ok to open separate issues/PRs for each  task or group below)

Create new python file
- [x] New python file available from main launcher/other ( #457 )
- [x] New python file available from file->new->python file ( #603 )

Icons
- [x] Editor icons visible from: launcher/other, file->new->python/r file, file browser when a `.py` or `.r` file is listed ( #2216 )

Open Python/R Editor
- [x] open blank Python/R Editor from launcher ( #457 )
- [x] open blank Python/R Editor from file->new->python file ( #603 )
- [x] open a `.py` or `.r` file should open Python/R Editor with expected content ( #2216 )
- [x] check content of menu when right click the editor tab (options should include `Python/R File`)( #2216 )

Python/R Editor toolbar
- [x] check for toolbar available ( #603 )
- [x] check for buttons and icons available: save, run, stop, select kernel drop down ( #603 )
- [x] verify all installed python (and only python) kernels listed on kernel select drop down ( #603) 

Output
- [x]  run code in the editor should open console output ( #2499 )
- [x]  console output scroll top/bottom buttons available ( #2499 )
- [x]  verify expected code output (#2507)
- [x]  run broken code should display error on console output (#2507)

**Comment by ptitzler** [comment]
Certainly. Done!

**Comment by Hema-Mathiyazhagan** [comment]
@karlaspuldaro I would like to work on few of this subtasks. could you please assign this one to me?

**Comment by karlaspuldaro** [comment]
All tasks marked as done
