### ISSUE TITLE
Elyra 1.0.0 release

### ISSUE THREAD

**Issue by lresende** [elyra-ai/elyra#555]
We have a few breaking changes coming up that might deserve a big release:
* JupyterLab 2.x
* Pipeline file format
* New API endpoint
* Code Snippet 

Let's use this issue to document what are the remaining items that need to be addressed before we can make an Elyra 1.0.0 release:

- [x] Add ability to create code-snippets from the UI (#556)
- [x] Finish the refactoring of the Elyra API endpoints (#513, #434)
- [x] Create conda-forge recipe (#455)
- [x] Bootstrapper package installation should use pinned versions (https://github.com/elyra-ai/kfp-notebook/issues/17)
- [x] Renaming of variables (#527)
- [x] TOC support for Python Editor (#520)

The plan then would be:
* Release 1.0.0 beta
* Release 1.0.0 rc-n (at least one per week)
* Release 1.0.0

**Comment by lresende** [comment]
Release has been published
