### ISSUE TITLE
Pipeline Validation Umbrella Issue

### ISSUE THREAD

**Issue by akchinSTC** [elyra-ai/elyra#682]
- [x] https://github.com/elyra-ai/elyra/issues/204 - Pipeline submission should fail and inform user if file dependency is not found 
- [x] https://github.com/elyra-ai/elyra/issues/256 - Should execution nodes be prevented from participating in circular references
- [x]  https://github.com/elyra-ai/elyra/issues/674 - File dependencies are treated as optional input
- [x]  https://github.com/elyra-ai/elyra/issues/663 - handle special characters in "output files" property
- [x]  https://github.com/elyra-ai/elyra/issues/660 - prevent creation of a circular graph
- [x]  https://github.com/elyra-ai/elyra/issues/658 - pipeline export should not be attempted if required parameters are missing
- [x]  https://github.com/elyra-ai/elyra/issues/653 - pipeline editor should indicate if there are problems in the flow configuration and where they are found
- [x] https://github.com/elyra-ai/elyra/issues/691 - A user should not be able to run, export or otherwise process an empty pipeline

**Comment by ajbozarth** [comment]
Though not pipeline validation should we include #737 here and make this general client side validation umbrella?
