### ISSUE TITLE
Add pipeline editor front end tests

### ISSUE THREAD

**Issue by karlaspuldaro** [elyra-ai/elyra#765]
Open pipeline
- [x] from launcher ( #364 )
- [x] from file -> new -> pipeline ( #940 )
- [x] open existing pipeline from file browser ( #940 )

Toolbar
- [x] visible icons ( #741 )

Empty pipeline
- [x] expected disabled toolbar buttons ( #741 )

Simple pipeline
- [x] drag and drop notebooks to editor and connect them (#1075)
- [x] open notebook from node (#1095)
- [x] expected enabled/disabled toolbar buttons ( #940 )
- [x] check node properties validation ( #940 )
- [x] create a pipeline runtime config ( #940 )
- [x] submit pipeline form validation ( #940 )
- [x] export pipeline form validation ( #940 )
- [x] submit pipeline (end to end) (#1075)
- [x] export pipeline (end to end, check if saved file exists in file browser) (#1095)
