### ISSUE TITLE
Make Elyra pipelines more flexible to enable better support for sharing via GitHub or other packaging

### ISSUE THREAD

**Issue by ajbozarth** [elyra-ai/elyra#822]
Umbrella task for handling pipeline editor enhancements focused around enabling "moving" pipelines

- [x] Validate pipeline which includes validation of file location #815
   - [x] Consider developing lifecycle, some types of validation only applies to when executing versus opening/saving
- [x] Enhance the pipeline editor to enable updates to the location of the notebook (including changing the notebook) #732
- [x] Support relative location of the notebook (relative to pipeline file) #823 
   - [x] When opening
   - [x] When drag-and-drop
   - [x] When submitting the pipeline
- [x] Pipeline migration #825
- [x] Documentation
   - [x] Best practices (Elyra 1.0) #820
   - [x] Validation #824

This umbrella should address the following issues:
#608 #659 #815

**Comment by ajbozarth** [comment]
Note: all issues under this umbrella now have open or merged PRs
