### ISSUE TITLE
JupyterLab 3.0 Release (umbrella issue)

### ISSUE THREAD

**Issue by kevin-bates** [elyra-ai/elyra#832]
JupyterLab's 3.0 release will be based on Jupyter Server - rather than Notebook - among other things.  This issue is created to track issues related to that effort.

Back-end tasks:
- [x] Convert server tests to Jupyter Server's framework #831
- [x] Rework server extension interface to Jupyter Server #834

Front-end tasks:
- [x] Clean up build
    - [x] Remove redundant build steps
    - [x] Figure out if new build files can be created dynamically on build (look into how core does it)
- [x] Get theme extension working
- [x] Get pipeline extension working
- [x] Test functionality that appears to be working 
- [x] Lab icon redundant import issue has returned

Issues found during integration:
- [x] Run and Export buttons are disabled on pipelines #1010
- [x] Notebook and Python script files cannot be dragged onto canvas #1012
- [x] Notebook and Python files cannot be opened by double-clicking node #1015

**Comment by ajbozarth** [comment]
Copying my notes from scrum here for reference:

>Worked on switching to Lab 3.0 alpha 14 (beta wasn't fully published yet) and ran into issues with the move to the federated build system. This Issue looks like it will be creating transition scripts for our build files, but as far as I tried, it's not yet working. It is probably worth waiting until there is more documentation around the new build system before spending more dev hours on transitioning to it.

**Comment by ajbozarth** [comment]
3.0 changeling for reference: https://jupyterlab.readthedocs.io/en/latest/getting_started/changelog.html

Task that need to be handled:
- [] Clean up build
    - [] Remove redundant build steps
    - [] Figure out if new build files can be created dynamically on build (look into how core does it)
- [] Get them extension working
- [] Get pipeline extension working
- [] Test functionality that appears to be working 
- [] lab icon redundant import issue has returned

Non-blocking upgrades to consider:
- [] Support translation
- [] Add debugger support to python editor
- [] Support single document mode?

**Comment by ajbozarth** [comment]
In an attempt to minimize the build changes I tried switching back to not using federated build, but hit a error, I've opened the following issue on lab to find a solution https://github.com/jupyterlab/jupyterlab/issues/9203 
If this can be solved it would address the `Clean up build` bullet.

**Comment by kevin-bates** [comment]
I notice the default configuration directory is changing from [`jupyter_notebook_config.d`](https://github.com/elyra-ai/elyra/blob/master/setup.py#L33) to [`jupyter_server_config.d`](https://github.com/elyra-ai/elyra/blob/jupyterlab3/setup.py#L33) and referenced in other places.  Do we need to consider some kind of upgrade script or instructions?  Might there also be pipeline updates for the 2.0 efforts?

**Comment by lresende** [comment]
I believe this is already handled on #1063 
```
auto_extension_path = "./etc/config/jupyter_notebook_config.d/*.json"
auto_extension_path = "./etc/config/jupyter_server_config.d/elyra.json" # TODO change back to include git
```

**Comment by kevin-bates** [comment]
I guess I was assuming that users may have added information to their `elyra.json` file or even marked the elyra extension as disabled for the moment.  Our objects do have configurable traits where this kind of thing would be configured (I think).  Are we doing anything to preserve configuration settings when an existing user upgrades from elyra 1.x to elyra 2.x?
